steps:

- checkout: self
  clean: true

- task: VSBuild@1
  displayName: Build
  inputs:
    solution: AutoCodeFix.sln
    configuration: Release
    msbuildArgs: '/restore /bl:"$(Build.ArtifactStagingDirectory)\build.binlog" /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)'

- task: VSTest@2
  displayName: Test
  inputs:
    testAssemblyVer2: src\AutoCodeFix.Tests\bin\*\AutoCodeFix.Tests.dll
    runInParallel: 'true'
    codeCoverageEnabled: 'true'
    publishRunAttachments: 'true'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: out
    ArtifactType: Container
  condition: always()
