//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCodeFix.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoCodeFix.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer assembly {0} is incompatible with {1}. Must reference Microsoft.CodeAnalysis version {2} or greater..
        /// </summary>
        internal static string ACF001 {
            get {
                return ResourceManager.GetString("ACF001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load analyzer assembly {0}: {1}..
        /// </summary>
        internal static string ACF002 {
            get {
                return ResourceManager.GetString("ACF002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get types from assembly {0}: {1}..
        /// </summary>
        internal static string ACF003 {
            get {
                return ResourceManager.GetString("ACF003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create analyzer {0}: {1}.
        /// </summary>
        internal static string ACF004 {
            get {
                return ResourceManager.GetString("ACF004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate a code fix for the following specified fixable diagnostics: {0}..
        /// </summary>
        internal static string ACF005 {
            get {
                return ResourceManager.GetString("ACF005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply code action &apos;{0}&apos; for diagnostic {1}: {2}: {3}..
        /// </summary>
        internal static string ACF006 {
            get {
                return ResourceManager.GetString("ACF006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code fix action found for diagnostic {0}: {1}..
        /// </summary>
        internal static string ACF007 {
            get {
                return ResourceManager.GetString("ACF007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No applicable changes were provided by the code action &apos;{0}&apos; for diagnostic {1}: {2}..
        /// </summary>
        internal static string ACF008 {
            get {
                return ResourceManager.GetString("ACF008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto fix {0} was specified as NoWarn and therefore cannot be fixed..
        /// </summary>
        internal static string ACF009 {
            get {
                return ResourceManager.GetString("ACF009", resourceCulture);
            }
        }
    }
}
